name: Dev CI
on:
  pull_request:
    paths-ignore:
      - samples/**
  push:
    paths-ignore:
      - samples/**
    branches:
      - ci/**

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
