name: Dev CI
on:
  push:
    paths-ignore:
      - samples/**
    branches-ignore:
      - master

jobs:
  test:
    uses: ./.github/workflows/run-tests.yml
  publish:
    needs: [ test ]
    uses: ./.github/workflows/publish-snapshot.yml
    secrets: inherit
    with:
      add-branch-suffix: true
